### PR TITLE
Update Author, URL, License

### LINKED ISSUE #31: Update Author, URL, License ID
Update the plugin's header information for Author, URI and add the license ID to the updater

### PR DESCRIPTION
**Pull request by mihaijoldis**
Fixes #31

### CODE REVIEW

**Review by LisaCee — CHANGES_REQUESTED** [review]
Will you update the author and site in readme.txt while we're here?

**Review by robincornett — COMMENTED** [review]
This looks great, but @mihaijoldis would you be willing to go ahead and set up the plugin header correctly, so that each line inside begins with the ` * ` (I know this is how it came but I would love to have it correct)? eg:

```php
/**
 * Plugin Name: Easy Digital Downloads - Per Product Emails
 * Plugin URI: https://easydigitaldownloads.com/downloads/per-product-emails/
 * etc.
 * /
```

**Comment by mihaijoldis** [comment]
I will review those later and update

**Comment by mihaijoldis** [comment]
@robincornett @LisaCee ready for recheck

**Review by robincornett — APPROVED** [review]
Note that the settings link will technically be correct only when the settings PR has been merged, but even now, it goes to the main extensions settings screen.

**Review by ashleyfae — APPROVED** [review]

**Pull request merged**
